### ISSUE TITLE
Problem with Right to Left direction

### ISSUE THREAD

**Issue by hosseinpanahi** [brenna/csshexagon#4]
when direction is rtl the background image of hexagon is messed up, an easy fix can be just adding direction: ltr to the .hexagon class in generated css

**Comment by brenna** [comment]
This tool assumes `direction: ltr` as it does other common defaults like `box-sizing: border-box`. I'd like to keep the generated css a minimal as possible. Those requiring `direction: ltr` specifically can add it to their own css as needed.
