### ISSUE TITLE
Bad code output

### ISSUE THREAD

**Issue by ligockym** [brenna/csshexagon#5]
Hello, 

when I generate code for hexagon with border in application, it looks good but the result in jsfiddle and my page looks bad.

JSfiddle: https://jsfiddle.net/L2cazftz/

**Comment by brenna** [comment]
Please try re-generating the code from the site again. My guess is something has been changed in the JS fiddle code after it was cut and paste, but I can't track down where from the output alone.

**Comment by ligockym** [comment]
It didn´t help. I tried it in Codepen, too.

**Comment by brenna** [comment]
Can you please provide a list of steps taken on the app to reproduce the
bug, so I can try myself and investigate further? It's hard to trace from
the output code alone.

On Tuesday, 29 December 2015, Marián Ligocký <notifications@github.com>
wrote:

> It didn´t help. I tried it in Codepen, too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brenna/csshexagon/issues/5#issuecomment-167794371>.
>


-- 

Brenna O'Brien

416-526-2003
hi@brennaobrien.com
@brnnbrn <http://twitter.com/brnnbrn>

**Comment by ligockym** [comment]
Set:
- height to 140px
- add border (5px).

That´s all, after you look at it in jsfiddle it doesn´t look like at your page. (https://jsfiddle.net/zh68v4xL/)

**Comment by brenna** [comment]
The app assumes you're using `box-sizing: border-box` on all elements, but this is not a default in jsfiddle. 

To fix, add `box-sizing: border-box;` to the `.hexagon` and  `.hexagon:before, .hexagon:after` slectors  or declare it as a global style for your project: 

```
*, *:before, *:after {
  box-sizing: border-box;
}
```
